apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: salmomascarenhas/auth-app
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
